import js from '@eslint/js';
import globals from 'globals';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';

/**
 * Flat config. Pinned to ESLint 9 on purpose: eslint-plugin-react@7.37.5 declares
 * peer `eslint ^3..^9.7` and has no ESLint 10 support yet. Bump both together when it lands.
 */
export default [
    {
        ignores: [
            'node_modules/**',
            'public/**',
            'storage/**',
            'vendor/**',
            'bootstrap/ssr/**',
            // separate Node service with its own toolchain
            'whatsapp-service/**',
            // generated by spatie/laravel-pdf + Ziggy
            'resources/js/ziggy.js',
        ],
    },
    js.configs.recommended,
    {
        files: ['**/*.{js,jsx}'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                ...globals.browser,
                route: 'readonly', // Ziggy global from the @routes Blade directive
                Ziggy: 'readonly',
            },
            parserOptions: {
                ecmaFeatures: { jsx: true },
            },
        },
        settings: {
            react: { version: '19.0' },
        },
        plugins: {
            react,
            'react-hooks': reactHooks,
        },
        rules: {
            ...react.configs.flat.recommended.rules,
            ...react.configs.flat['jsx-runtime'].rules,
            ...reactHooks.configs.flat['recommended-latest'].rules,

            // automatic JSX runtime — no need to import React
            'react/react-in-jsx-scope': 'off',

            // plain JSX, no propTypes anywhere in this codebase
            'react/prop-types': 'off',

            // The repo's layout convention is `Page.layout = (page) => <Layout children={page} />`
            // across ~88 pages. The rule is a legacy-pattern warning, not a defect here.
            'react/no-children-prop': 'off',

            // The React Compiler-era rules below are structurally sound but noisy for this
            // codebase (Inertia prop -> local state syncing, browser globals, inline JSX).
            // Kept visible as warnings; promote to 'error' after the backlog is cleared.
            'react-hooks/immutability': 'warn',
            'react-hooks/set-state-in-effect': 'warn',
            'react-hooks/static-components': 'warn',
            'react-hooks/preserve-manual-memoization': 'warn',

            // warn, not error: adoption is incremental. Flip to 'error' once clean.
            'no-unused-vars': [
                'warn',
                { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true },
            ],
            'no-console': ['warn', { allow: ['warn', 'error'] }],
        },
    },
    {
        // config files and the Node service are CommonJS / Node-side
        files: ['*.config.js', 'postcss.config.js', 'tailwind.config.js'],
        languageOptions: {
            globals: { ...globals.node },
        },
    },
];
